- hosts: iaas-node
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - nova-compute
      - neutron-linuxbridge-agent
  - name: copy nova.conf
    template:
      src: nova/nova.conf
      dest: /etc/nova/nova.conf
      owner: root
      group: root
      mode: '0644'
  - name: get my ip address
    shell: ifconfig | grep 'inet addr:192.168.1.' | awk '{print $2}' | awk -F: '{print $2}'
    register: myip
    args:
      executable: /bin/bash
  - name: replace my ip address
    replace:
      path: /etc/nova/nova.conf
      regexp: 'my_ip ='
      replace: '\1my_ip = {{myip.stdout}}\2'
  - name: copy neutron.conf
    template:
      src: neutron/neutron.conf
      dest: /etc/neutron/neutron.conf
      owner: root
      group: root
      mode: '0644'
  - name: copy linuxbridge_agent.ini
    template:
      src: neutron/linuxbridge_agent.ini
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      owner: root
      group: root
      mode: '0644'
  - name: reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
