- hosts: e2e
  user: ubuntu
  tasks:
  - name: copy k8s config file
    template:
      src: ~/.kube/config
      dest: /home/ubuntu/admin.conf
      mode: '0644'
  - name: Make dir of e2e logs
    file:
      path: /home/ubuntu/e2e_logs
      state: directory
  - name: run e2e
    shell: cd /home/ubuntu/go/src/k8s.io/kubernetes; export GOPATH=/home/ubuntu/go; export KUBERNETES_CONFORMANCE_TEST=true; export KUBECONFIG=/home/ubuntu/admin.conf; go run hack/e2e.go -- --provider=skeleton -v --test --test_args="--ginkgo.focus=\[Conformance\] -v=8" > /home/ubuntu/e2e_logs/e2e_`date '+%F_%T' | sed s/[:-]//g`.log
