- hosts: e2e
  user: ubuntu
  tasks:
  - name: copy k8s config file
    template:
      src: ~/.kube/config
      dest: /home/ubuntu/admin.conf
      mode: '0644'
  - name: run e2e
    shell: cd $GOPATH/src/k8s.io/kubernetes; go run hack/e2e.go -- --provider=skeleton -v --test --test_args="--ginkgo.focus=\[Conformance\]"
