apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret-as-variable
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-01
            key: password
