apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secret-01
spec:
  containers:
  - name: pod-using-secret-01
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: secret-01
