- hosts: all
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - python-pexpect
      - software-properties-common
  - name: Add cloud-archive
    expect:
      command: add-apt-repository cloud-archive:queens
      responses:
        "Press \\[ENTER\\] to continue": ""
  - name: Update apt
    shell: apt-get update
  - name: Upgrade package
    shell: apt-get -y dist-upgrade
