- hosts: master
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: kubeadm init
    shell: kubeadm reset; sleep 3; kubeadm init | grep "kubeadm join" > /tmp/kubeadm_join.sh
  - name: scp kubeadm_join.sh
    fetch:
      src: /tmp/kubeadm_join.sh
      dest: /tmp/kubeadm_join.sh
      flat: yes
  - name: change admin.conf
    file:
      path: /etc/kubernetes/admin.conf
      mode: 0644
- hosts: master
  user: ubuntu
  tasks:
  - name: kube conf
    shell: grep -v KUBECONFIG $HOME/.bashrc > /tmp/bashrc; mv /tmp/bashrc $HOME/.bashrc; echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> $HOME/.bashrc
- hosts: master
  user: ubuntu
  tasks:
  - name: setup weave-kube
    shell: sleep 3; export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl apply -f https://git.io/weave-kube-1.6
  - name: make the manager schedulable
    shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl taint nodes `uname -n` node-role.kubernetes.io/master:NoSchedule-
