- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Copy netplan config file
    template:
      src: netplan/60-localnet-init.yaml
      dest: /etc/netplan/60-localnet-init.yaml
      owner: root
      group: root
      mode: '0644'
  - name: reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true
