- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Keystone Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - mariadb-server
      - python-pymysql
      - vim
      - keystone
      - apache2
      - libapache2-mod-wsgi-py3
      - python-mysqldb
      - python-openstackclient
  - name: delete database table
    mysql_db:
      name: keystone
      state: absent
  - name: Keystone create database table
    mysql_db:
      name: keystone
      state: present
      encoding: utf8
  - name: Keystone create database user
    mysql_user:
      name: keystone
      password: KEYSTONE_DBPASS
      priv: 'keystone.*:ALL'
      state: present
      host: 'localhost'
      append_privs: yes
  - name: Keystone create database user
    mysql_user:
      name: keystone
      password: KEYSTONE_DBPASS
      priv: 'keystone.*:ALL'
      state: present
      host: '%'
      append_privs: yes
  - name: Keystone configuration file copy
    template:
      src: keystone/keystone.conf
      dest: /etc/keystone/keystone.conf
      owner: root
      group: root
      mode: '0644'
  - name: Keystone add adminrc setting
    shell: echo "source /home/ubuntu/adminrc" >> /home/ubuntu/.bashrc
  - name: Keystone adminrc file copy
    template:
      src: adminrc
      dest: /home/ubuntu/adminrc
      owner: ubuntu
      group: ubuntu
      mode: '0644'
  - name: Keystone add adminrc setting
    shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  - name: Keystone fernet_setup
    shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  - name: Keystone credential_setup
    shell: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  - name: Keystone bootstrap
    shell: keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://iaas-ctrl:5000/v3/ --bootstrap-internal-url http://iaas-ctrl:5000/v3/ --bootstrap-public-url http://iaas-ctrl:5000/v3/ --bootstrap-region-id RegionOne
  - name: Set apache
    shell: sed -i s/"#ServerName www.example.com"/"ServerName iaas-ctrl"/ /etc/apache2/sites-available/000-default.conf
  - name: apache reboot
    shell: service apache2 restart

