- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
  - name: delete neutron database table if exists
    mysql_db:
      name: neutron
      state: absent
  - name: create neutron database table
    mysql_db:
      name: neutron
      state: present
      encoding: utf8
  - name: glant all privs to neutron user for neutron 1
    mysql_user:
      name: neutron
      password: NEUTRON_DBPASS
      priv: 'neutron.*:ALL'
      state: present
      host: 'localhost'
      append_privs: yes
  - name: glant all privs to neutron user for neutron 2
    mysql_user:
      name: neutron
      password: NEUTRON_DBPASS
      priv: 'neutron.*:ALL'
      state: present
      host: '%'
      append_privs: yes
  - name: copy neutron.conf
    template:
      src: neutron/neutron.conf
      dest: /etc/neutron/neutron.conf
      owner: root
      group: root
      mode: '0644'
  - name: copy ml2_conf.ini
    template:
      src: neutron/ml2_conf.ini
      dest: /etc/neutron/plugins/ml2/ml2_conf.ini
      owner: root
      group: root
      mode: '0644'
  - name: copy linuxbridge_agent.ini
    template:
      src: neutron/linuxbridge_agent.ini
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      owner: root
      group: root
      mode: '0644'
  - name: copy dhcp_agent.ini
    template:
      src: neutron/dhcp_agent.ini
      dest: /etc/neutron/dhcp_agent.ini
      owner: root
      group: root
      mode: '0644'
  - name: copy metadata_agent.ini
    template:
      src: neutron/metadata_agent.ini
      dest: /etc/neutron/metadata_agent.ini
      owner: root
      group: root
      mode: '0644'
  - name: db_sync
    shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  - name: reboot
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: true

