- hosts: iaas-ctrl
  user: ubuntu
  tasks:
  - name: create flavor m1.tiny
    shell: source adminrc; openstack --os-region-name="$REGION_NAME" flavor create --id 1 --ram 512 --disk 1 --vcpus 1 m1.tiny
    args:
      executable: /bin/bash
  - name: create flavor m1.small
    shell: source adminrc; openstack --os-region-name="$REGION_NAME" flavor create --id 2 --ram 2048 --disk 20 --vcpus 1 m1.small
    args:
      executable: /bin/bash
  - name: create flavor m1.medium
    shell: source adminrc; openstack --os-region-name="$REGION_NAME" flavor create --id 3 --ram 4096 --disk 40 --vcpus 2 m1.medium
    args:
      executable: /bin/bash
  - name: create flavor m1.large
    shell: source adminrc; openstack --os-region-name="$REGION_NAME" flavor create --id 4 --ram 8192 --disk 80 --vcpus 4 m1.large
    args:
      executable: /bin/bash
  - name: download ubuntu image
    shell: wget https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    args:
      executable: /bin/bash
  - name: register ubuntu image to glance
    shell: source adminrc; openstack image create --container-format bare --disk-format qcow2 --file bionic-server-cloudimg-amd64.img Ubuntu-18.04-x86_64
    args:
      executable: /bin/bash

