- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - cinder-volume
      - lvm2
      - thin-provisioning-tools
  - name: create a backing file for LVM
    shell: truncate /var/lib/cinder/lvm-backing --size 100G
  - name: change the mod of the backing file
    file: path=/var/lib/cinder/lvm-backing owner=cinder group=cinder mode=0644
  - name: create a loopback device for the backing file
    shell: losetup -f --show /var/lib/cinder/lvm-backing
    register: mydevice
  - name: create a vg
    shell: vgcreate cinder-volumes {{mydevice.stdout}}
  - name: copy cinder-setup-backing-file
    template:
      src: cinder/cinder-setup-backing-file
      dest: /etc/init.d/cinder-setup-backing-file
      owner: root
      group: root
      mode: '0755'
  - name: create a symlink for cinder-setup-backing-file
    file:
      src: /etc/init.d/cinder-setup-backing-file
      dest: /etc/rc3.d/S10cinder-setup-backing-file
      owner: root
      group: root
      state: link
