- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - cinder-volume
      - lvm2
      - thin-provisioning-tools
  - name: delete cinder database table if exists
    mysql_db:
      name: cinder
      state: absent
  - name: create cinder database table
    mysql_db:
      name: cinder
      state: present
      encoding: utf8
  - name: glant all privs to cinder user for cinder 1
    mysql_user:
      name: cinder
      password: CINDER_DBPASS
      priv: 'cinder.*:ALL'
      state: present
      host: 'localhost'
      append_privs: yes
  - name: glant all privs to cinder user for cinder 2
    mysql_user:
      name: cinder
      password: CINDER_DBPASS
      priv: 'cinder.*:ALL'
      state: present
      host: '%'
      append_privs: yes
  - name: copy cinder-setup-backing-file
    template:
      src: cinder/cinder-setup-backing-file
      dest: /etc/init.d/cinder-setup-backing-file
      owner: root
      group: root
      mode: '0755'
  - name: create a symlink for cinder-setup-backing-file
    file:
      src: /etc/init.d/cinder-setup-backing-file
      dest: /etc/rc5.d/S10cinder-setup-backing-file
      owner: root
      group: root
      state: link
  - name: copy cinder.conf
    template:
      src: cinder/cinder.conf
      dest: /etc/cinder/cinder.conf
      owner: root
      group: cinder
      mode: '0644'
  - name: create a backing file for LVM
    shell: truncate /var/lib/cinder/lvm-backing --size 100G
  - name: change the mod of the backing file
    file: path=/var/lib/cinder/lvm-backing owner=cinder group=cinder mode=0644
  - name: create a loopback device for the backing file
    shell: losetup -f --show /var/lib/cinder/lvm-backing
    register: mydevice
  - name: create a vg
    shell: vgcreate cinder-volumes {{mydevice.stdout}}
