- hosts: iaas-ctrl
  become: true
  become_user: root
  user: ubuntu
  tasks:
  - name: Install packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - tox
      - qemu-utils
      - git
      - kpartx
      - debootstrap
      - octavia-api
      - octavia-health-manager
      - octavia-housekeeping
      - octavia-worker
      - python3-octavia
      - python3-octaviaclient
  - name: chmod /etc/octavia
    file: path=/etc/octavia owner=octavia group=octavia mode=0755
  - name: copy octavia.conf
    template:
      src: octavia/octavia.conf
      dest: /etc/octavia/octavia.conf
      owner: octavia
      group: octavia
      mode: '0644'
  - name: copy octaviarc
    template:
      src: octavia/octaviarc
      dest: /etc/octavia/octaviarc
      owner: octavia
      group: octavia
      mode: '0644'
  - name: create octavia user
    shell: source adminrc; openstack user create --domain default --password OCTAVIA_PASS octavia
    args:
      executable: /bin/bash
  - name: add octavia role
    shell: source adminrc; openstack role add --project service --user octavia admin
    args:
      executable: /bin/bash
  - name: create octavia management network
    shell: source adminrc; openstack network create lb-mgmt-net
    args:
      executable: /bin/bash
  - name: create octavia management subnet
    shell: source adminrc; openstack subnet create --subnet-range 192.168.0.0/24 --allocation-pool start=192.168.0.2,end=192.168.0.200 --network lb-mgmt-net lb-mgmt-subnet
    args:
      executable: /bin/bash
  - name: get the ID of lb-mgmt-net
    shell: source adminrc; openstack network show lb-mgmt-net -c id -f value
    register: lbmgmtnet
    args:
      executable: /bin/bash
  - name: replace the ID of lb-mgmt-net for octavia.conf
    replace:
      name: /etc/octavia/octavia.conf
      regexp: 'lb-mgmt-net_id'
      replace: '{{lbmgmtnet.stdout}}'
  - name: create octavia security group
    shell: source /etc/octavia/octaviarc; openstack security group create lb-mgmt-sec-grp
    args:
      executable: /bin/bash
  - name: create octavia security group rule for icmp
    shell: source /etc/octavia/octaviarc; openstack security group rule create --protocol icmp lb-mgmt-sec-grp
    args:
      executable: /bin/bash
  - name: create octavia security group rule for ssh
    shell: source /etc/octavia/octaviarc; openstack security group rule create --protocol tcp --dst-port 22 lb-mgmt-sec-grp
    args:
      executable: /bin/bash
  - name: create octavia security group rule for tcp/9443
    shell: source /etc/octavia/octaviarc; openstack security group rule create --protocol tcp --dst-port 9443 lb-mgmt-sec-grp
    args:
      executable: /bin/bash
  - name: create health-mgr security group
    shell: source adminrc; openstack security group create lb-health-mgr-sec-grp
    args:
      executable: /bin/bash
  - name: create health-mgr security group rule
    shell: source adminrc; openstack security group rule create --protocol udp --dst-port 5555 lb-health-mgr-sec-grp
    args:
      executable: /bin/bash
  - name: get the ID of lb-mgmt-sec-grp
    shell: source /etc/octavia/octaviarc; openstack security group show lb-mgmt-sec-grp -c id -f value
    register: lbmgmtsecgrp
    args:
      executable: /bin/bash
  - name: replace the ID of lb-mgmt-sec-grp for octavia.conf
    replace:
      name: /etc/octavia/octavia.conf
      regexp: 'lb-mgmt-sec-grp_id'
      replace: '{{lbmgmtsecgrp.stdout}}'
  - name: get the ID of lb-mgmt-subnet
    shell: source adminrc; openstack subnet show lb-mgmt-subnet -c id -f value
    register: lbmgmtsubnet
    args:
      executable: /bin/bash
  - name: create octavia management port
    shell: source adminrc; openstack port create --security-group lb-health-mgr-sec-grp --device-owner Octavia:health-mgr --host=iaas-ctrl --network lb-mgmt-net --fixed-ip subnet={{lbmgmtsubnet.stdout}},ip-address=192.168.0.4 octavia-health-manager-listen-port
    args:
      executable: /bin/bash
  - name: create octavia services
    shell: source adminrc; openstack service create --name octavia --description "OpenStack Load Balancer" load-balancer
    args:
      executable: /bin/bash
  - name: create octavia public endpoints
    shell: source adminrc; openstack endpoint create --region RegionOne load-balancer public http://iaas-ctrl:9876
    args:
      executable: /bin/bash
  - name: create octavia internal endpoints
    shell: source adminrc; openstack endpoint create --region RegionOne load-balancer internal http://iaas-ctrl:9876
    args:
      executable: /bin/bash
  - name: create octavia admin endpoints
    shell: source adminrc; openstack endpoint create --region RegionOne load-balancer admin http://iaas-ctrl:9876
    args:
      executable: /bin/bash
  - name: cleanup temporary directory for octavia repo
    file: path=/tmp/octavia state=absent
  - name: create temporary directory for octavia repo
    file: path=/tmp/octavia state=directory owner=octavia group=octavia mode=0755
  - name: clone octavia repo
    shell: git clone https://github.com/openstack/octavia.git /tmp/octavia/
    args:
      executable: /bin/bash
  - name: create an amphora image
    shell: cd /tmp/octavia/diskimage-create; tox -e build
    args:
      executable: /bin/bash
  - name: upload the amphora image
    shell: source adminrc; openstack image create --disk-format qcow2 --container-format bare --private --tag amphora --file /tmp/octavia/diskimage-create/amphora-x64-haproxy.qcow2 amphora-x64-haproxy
    args:
      executable: /bin/bash
  - name: tag the amphora image
    shell: source adminrc; openstack image set --tag amphora amphora-x64-haproxy
    args:
      executable: /bin/bash
  - name: create a flavor for amphora instance
    shell: source adminrc; openstack flavor create --id 200 --vcpus 1 --ram 1024 --disk 10 "amphora" --private
    args:
      executable: /bin/bash
  - name: chown /etc/octavia directory
    file: path=/etc/octavia owner=octavia group=octavia
  - name: create certs directory
    file: path=/etc/octavia/certs state=directory owner=octavia group=octavia mode=0700
  - name: create certs private directory
    file: path=/etc/octavia/certs/private state=directory owner=octavia group=octavia mode=0700
  - name: create the certificates
    shell: cd /tmp/octavia/bin; /tmp/octavia/bin/create_dual_intermediate_CA.sh
    args:
      executable: /bin/bash
  - name: copy certs 1-5
    shell: cp /tmp/octavia/bin/dual_ca/etc/octavia/certs/server_ca.cert.pem /etc/octavia/certs/
    args:
      executable: /bin/bash
  - name: copy certs 2-5
    shell: cp /tmp/octavia/bin/dual_ca/etc/octavia/certs/server_ca-chain.cert.pem /etc/octavia/certs/
    args:
      executable: /bin/bash
  - name: copy certs 3-5
    shell: cp /tmp/octavia/bin/dual_ca/etc/octavia/certs/server_ca.key.pem /etc/octavia/certs/private/
    args:
      executable: /bin/bash
  - name: copy certs 4-5
    shell: cp /tmp/octavia/bin/dual_ca/etc/octavia/certs/client_ca.cert.pem /etc/octavia/certs/
    args:
      executable: /bin/bash
  - name: copy certs 5-5
    shell: cp /tmp/octavia/bin/dual_ca/etc/octavia/certs/client.cert-and-key.pem /etc/octavia/certs/private/
    args:
      executable: /bin/bash
  - name: chmod certs 1-5
    file: path=/etc/octavia/certs/server_ca.cert.pem owner=octavia group=octavia mode=0600
  - name: chmod certs 2-5
    file: path=/etc/octavia/certs/server_ca-chain.cert.pem owner=octavia group=octavia mode=0600
  - name: chmod certs 3-5
    file: path=/etc/octavia/certs/private/server_ca.key.pem owner=octavia group=octavia mode=0600
  - name: chmod certs 4-5
    file: path=/etc/octavia/certs/client_ca.cert.pem owner=octavia group=octavia mode=0600
  - name: chmod certs 5-5
    file: path=/etc/octavia/certs/private/client.cert-and-key.pem owner=octavia group=octavia mode=0600
  - name: create ssh key directory
    file: path=/etc/octavia/.ssh state=directory owner=octavia group=octavia mode=0700
  - name: create ssh key
    shell: su -s /bin/sh -c 'ssh-keygen -b 2048 -t rsa -N "" -f /etc/octavia/.ssh/octavia_ssh_key' octavia
  - name: chmod ssh key directory
    file: path=/etc/octavia/.ssh owner=octavia group=octavia mode=0700
  - name: chmod ssh private key
    file: path=/etc/octavia/.ssh/octavia_ssh_key owner=octavia group=octavia mode=0600
  - name: chmod ssh public key
    file: path=/etc/octavia/.ssh/octavia_ssh_key.pub owner=octavia group=octavia mode=0600
  - name: create keypair for SSH login to amphorae
    shell: source /etc/octavia/octaviarc; openstack keypair create --public-key /etc/octavia/.ssh/octavia_ssh_key.pub octavia_ssh_key
    args:
      executable: /bin/bash
  - name: delete octavia database table if exists
    mysql_db:
      name: octavia
      state: absent
  - name: create octavia database table
    mysql_db:
      name: octavia
      state: present
      encoding: utf8
  - name: glant all privs to octavia user for octavia 1
    mysql_user:
      name: octavia
      password: OCTAVIA_DBPASS
      priv: 'octavia.*:ALL'
      state: present
      host: 'localhost'
      append_privs: yes
  - name: glant all privs to octavia user for octavia 2
    mysql_user:
      name: octavia
      password: OCTAVIA_DBPASS
      priv: 'octavia.*:ALL'
      state: present
      host: '%'
      append_privs: yes
  - name: Octavia db_sync
    shell: su -s /bin/sh -c "octavia-db-manage --config-file /etc/octavia/octavia.conf upgrade head" octavia
