name: Typo Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-typo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check typo
        run: |
          ./tests/check_typo.sh

